# Generated by Django 5.0.3 on 2024-03-11 11:30

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_zone',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[users.validators.check_time_zone], verbose_name='Часовой пояс'),
        ),
    ]
