# Generated by Django 5.0.3 on 2024-03-06 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('time_to_start', models.TimeField(verbose_name='Начало')),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(verbose_name='Приятная ли это привычка?')),
                ('periodic', models.IntegerField(choices=[(0, 'Ежедневно'), (1, 'Еженедельно')], default=0, verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='Награда')),
                ('time_to_complete', models.IntegerField(verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(verbose_name='Публичная ли привычка?')),
                ('link_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_habits', to='habits.habit', verbose_name='Ссылка на привычку')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habit', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['id'],
            },
        ),
    ]
