# Generated by Django 5.0.3 on 2024-03-09 23:21

import django.db.models.deletion
import habits.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='link_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_habits', to='habits.habit', validators=[habits.validators.validate_link_habit_is_pleasant], verbose_name='Ссылка на привычку'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.IntegerField(validators=[habits.validators.validate_time_to_complete], verbose_name='Время на выполнение'),
        ),
    ]
